version: "3"

services:
  nginx:
    image: easybar/nginx:dev
    depends_on:
      - app
    environment:
      - DOCROOT=/srv/public
    volumes:
      - ./site/:/srv
#      - ./docker/logs/nginx/:/var/log/nginx/
#      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf

  app:
    image: easybar/php:7.2.9-dev
    depends_on:
      - db
    volumes:
      - ./site/:/srv

  db:
    image: mariadb:10.2.10
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: "easy_ride"
    volumes:
      - db-data:/var/lib/mysql

  db_admin:
    image: adminer
    links:
      - db
    ports:
      - 8081:8080
volumes:
  db-data: {}
