fos_rest:
    body_listener: true
    format_listener:
        rules:
            - { path: '^/', priorities: ['json'], fallback_format: json }
    exception:
        enabled: true
        exception_controller: 'fos_rest.exception.controller:showAction'
    param_fetcher_listener: true
    view:
        view_response_listener: 'force'
        formats:
            json: true
